export const IPC_CHANNELS = {
  recordingStart: 'recording:start',
  recordingStatus: 'recording:status',
  recordingStop: 'recording:stop',
  sessionsList: 'sessions:list',
  sessionsGet: 'sessions:get',
  exportsWrite: 'exports:write',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  executionStart: 'execution:start',
  executionStatus: 'execution:status',
  executionCancel: 'execution:cancel',
  executionUpdate: 'execution:update',
  credentialsSetPlaywrightPassword: 'credentials:set-playwright-password',
  credentialsClearPlaywrightPassword: 'credentials:clear-playwright-password',
} as const;
