import type { RecordedSession } from '@journeyforge/shared';

export const createPostSession: RecordedSession = {
  id: 'session-create-post',
  name: 'Create Post',
  baseUrl: 'http://localhost:3000',
  startedAt: 1711000000000,
  endedAt: 1711000015000,
  rawEvents: [
    {
      id: 'nav-login',
      type: 'navigation',
      timestamp: 1711000000000,
      pageUrl: 'http://localhost:3000/login',
      targetUrl: 'http://localhost:3000/login',
      trigger: 'goto',
    },
    {
      id: 'input-email',
      type: 'input',
      timestamp: 1711000000100,
      pageUrl: 'http://localhost:3000/login',
      locator: { strategy: 'label', value: 'Email' },
      value: 'q***@example.com',
      masked: true,
      fieldName: 'email',
    },
    {
      id: 'input-password',
      type: 'input',
      timestamp: 1711000000200,
      pageUrl: 'http://localhost:3000/login',
      locator: { strategy: 'label', value: 'Password' },
      value: '******',
      masked: true,
      fieldName: 'password',
    },
    {
      id: 'click-login',
      type: 'click',
      timestamp: 1711000000300,
      pageUrl: 'http://localhost:3000/login',
      locator: { strategy: 'role', value: 'button:로그인' },
      text: '로그인',
    },
    {
      id: 'req-login',
      type: 'network-request',
      timestamp: 1711000000320,
      requestId: 'req-login',
      method: 'POST',
      url: 'http://localhost:3000/api/auth/login',
      pageUrl: 'http://localhost:3000/login',
      resourceType: 'xhr',
      headers: { 'content-type': 'application/json' },
    },
    {
      id: 'res-login',
      type: 'network-response',
      timestamp: 1711000000460,
      requestId: 'req-login',
      status: 200,
      durationMs: 140,
      contentType: 'application/json',
    },
    {
      id: 'nav-products',
      type: 'navigation',
      timestamp: 1711000000600,
      pageUrl: 'http://localhost:3000/products',
      targetUrl: 'http://localhost:3000/products',
      trigger: 'history',
    },
    {
      id: 'click-create-link',
      type: 'click',
      timestamp: 1711000000800,
      pageUrl: 'http://localhost:3000/products',
      locator: { strategy: 'role', value: 'link:게시글 작성' },
      text: '게시글 작성',
    },
    {
      id: 'nav-post-new',
      type: 'navigation',
      timestamp: 1711000000900,
      pageUrl: 'http://localhost:3000/posts/new',
      targetUrl: 'http://localhost:3000/posts/new',
      trigger: 'history',
    },
    {
      id: 'input-title',
      type: 'input',
      timestamp: 1711000001100,
      pageUrl: 'http://localhost:3000/posts/new',
      locator: { strategy: 'label', value: 'Title' },
      value: 'Launch checklist',
      masked: false,
      fieldName: 'title',
    },
    {
      id: 'input-content',
      type: 'input',
      timestamp: 1711000001300,
      pageUrl: 'http://localhost:3000/posts/new',
      locator: { strategy: 'label', value: 'Content' },
      value: 'Write flow support is ready for review.',
      masked: false,
      fieldName: 'content',
    },
    {
      id: 'click-create',
      type: 'click',
      timestamp: 1711000001500,
      pageUrl: 'http://localhost:3000/posts/new',
      locator: { strategy: 'role', value: 'button:등록' },
      text: '등록',
    },
    {
      id: 'req-create-post',
      type: 'network-request',
      timestamp: 1711000001515,
      requestId: 'req-create-post',
      method: 'POST',
      url: 'http://localhost:3000/api/posts',
      pageUrl: 'http://localhost:3000/posts/new',
      resourceType: 'fetch',
      headers: { 'content-type': 'application/json' },
    },
    {
      id: 'res-create-post',
      type: 'network-response',
      timestamp: 1711000001695,
      requestId: 'req-create-post',
      status: 201,
      durationMs: 180,
      contentType: 'application/json',
    },
    {
      id: 'req-created-detail',
      type: 'network-request',
      timestamp: 1711000001710,
      requestId: 'req-created-detail',
      method: 'GET',
      url: 'http://localhost:3000/api/posts/101',
      pageUrl: 'http://localhost:3000/posts/new',
      resourceType: 'fetch',
      headers: { accept: 'application/json' },
    },
    {
      id: 'res-created-detail',
      type: 'network-response',
      timestamp: 1711000001790,
      requestId: 'req-created-detail',
      status: 200,
      durationMs: 80,
      contentType: 'application/json',
    },
    {
      id: 'nav-created-post',
      type: 'navigation',
      timestamp: 1711000001840,
      pageUrl: 'http://localhost:3000/posts/101',
      targetUrl: 'http://localhost:3000/posts/101',
      trigger: 'history',
    },
  ],
};
