import type { RecordedSession } from '@journeyforge/shared';

export const loginSearchDetailSession: RecordedSession = {
  id: 'session-login-search-detail',
  name: 'Login Search Detail',
  baseUrl: 'http://localhost:3000',
  startedAt: 1710000000000,
  endedAt: 1710000010000,
  rawEvents: [
    {
      id: 'nav-login',
      type: 'navigation',
      timestamp: 1710000000000,
      pageUrl: 'http://localhost:3000/login',
      targetUrl: 'http://localhost:3000/login',
      trigger: 'goto',
    },
    {
      id: 'input-email',
      type: 'input',
      timestamp: 1710000000500,
      pageUrl: 'http://localhost:3000/login',
      locator: {
        strategy: 'label',
        value: 'Email',
      },
      value: 'qa@example.com',
      masked: true,
      fieldName: 'email',
    },
    {
      id: 'input-password',
      type: 'input',
      timestamp: 1710000000900,
      pageUrl: 'http://localhost:3000/login',
      locator: {
        strategy: 'label',
        value: 'Password',
      },
      value: '******',
      masked: true,
      fieldName: 'password',
    },
    {
      id: 'click-login',
      type: 'click',
      timestamp: 1710000001200,
      pageUrl: 'http://localhost:3000/login',
      locator: {
        strategy: 'role',
        value: 'button:로그인',
      },
      text: '로그인',
    },
    {
      id: 'req-login',
      type: 'network-request',
      timestamp: 1710000001220,
      requestId: 'req-1',
      method: 'POST',
      url: 'http://localhost:3000/api/auth/login',
      pageUrl: 'http://localhost:3000/login',
      resourceType: 'xhr',
      headers: {
        'content-type': 'application/json',
        authorization: 'Bearer should-not-leak',
      },
    },
    {
      id: 'res-login',
      type: 'network-response',
      timestamp: 1710000001380,
      requestId: 'req-1',
      status: 200,
      durationMs: 160,
      contentType: 'application/json',
    },
    {
      id: 'nav-products',
      type: 'navigation',
      timestamp: 1710000001600,
      pageUrl: 'http://localhost:3000/products',
      targetUrl: 'http://localhost:3000/products',
      trigger: 'redirect',
    },
    {
      id: 'input-search',
      type: 'input',
      timestamp: 1710000002100,
      pageUrl: 'http://localhost:3000/products',
      locator: {
        strategy: 'placeholder',
        value: '검색어',
      },
      value: '맥북',
      masked: false,
      fieldName: 'search',
    },
    {
      id: 'click-search',
      type: 'click',
      timestamp: 1710000002400,
      pageUrl: 'http://localhost:3000/products',
      locator: {
        strategy: 'role',
        value: 'button:검색',
      },
      text: '검색',
    },
    {
      id: 'req-products',
      type: 'network-request',
      timestamp: 1710000002420,
      requestId: 'req-2',
      method: 'GET',
      url: 'http://localhost:3000/api/products?keyword=%EB%A7%A5%EB%B6%81&page=0',
      pageUrl: 'http://localhost:3000/products',
      resourceType: 'fetch',
      headers: {
        accept: 'application/json',
      },
    },
    {
      id: 'res-products',
      type: 'network-response',
      timestamp: 1710000002560,
      requestId: 'req-2',
      status: 200,
      durationMs: 140,
      contentType: 'application/json',
    },
    {
      id: 'req-static',
      type: 'network-request',
      timestamp: 1710000002600,
      requestId: 'req-3',
      method: 'GET',
      url: 'http://localhost:3000/assets/app.css',
      pageUrl: 'http://localhost:3000/products',
      resourceType: 'stylesheet',
      headers: {},
    },
    {
      id: 'res-static',
      type: 'network-response',
      timestamp: 1710000002610,
      requestId: 'req-3',
      status: 200,
      durationMs: 10,
      contentType: 'text/css',
    },
    {
      id: 'req-analytics',
      type: 'network-request',
      timestamp: 1710000002650,
      requestId: 'req-4',
      method: 'POST',
      url: 'https://www.google-analytics.com/g/collect?v=2',
      pageUrl: 'http://localhost:3000/products',
      resourceType: 'fetch',
      headers: {},
    },
    {
      id: 'res-analytics',
      type: 'network-response',
      timestamp: 1710000002675,
      requestId: 'req-4',
      status: 204,
      durationMs: 25,
      contentType: 'text/plain',
    },
    {
      id: 'click-product-card',
      type: 'click',
      timestamp: 1710000003200,
      pageUrl: 'http://localhost:3000/products',
      locator: {
        strategy: 'text',
        value: 'MacBook Pro 14',
      },
      text: 'MacBook Pro 14',
    },
    {
      id: 'req-product-detail',
      type: 'network-request',
      timestamp: 1710000003240,
      requestId: 'req-5',
      method: 'GET',
      url: 'http://localhost:3000/api/products/42',
      pageUrl: 'http://localhost:3000/products',
      resourceType: 'fetch',
      headers: {
        accept: 'application/json',
      },
    },
    {
      id: 'res-product-detail',
      type: 'network-response',
      timestamp: 1710000003400,
      requestId: 'req-5',
      status: 200,
      durationMs: 160,
      contentType: 'application/json',
    },
    {
      id: 'nav-detail',
      type: 'navigation',
      timestamp: 1710000003550,
      pageUrl: 'http://localhost:3000/products/42',
      targetUrl: 'http://localhost:3000/products/42',
      trigger: 'click',
    },
  ],
};
