import type { RecordedSession } from '@journeyforge/shared';

export const updatePostSession: RecordedSession = {
  id: 'session-update-post',
  name: 'Update Post',
  baseUrl: 'http://localhost:3000',
  startedAt: 1712000000000,
  endedAt: 1712000016000,
  rawEvents: [
    {
      id: 'nav-login',
      type: 'navigation',
      timestamp: 1712000000000,
      pageUrl: 'http://localhost:3000/login',
      targetUrl: 'http://localhost:3000/login',
      trigger: 'goto',
    },
    {
      id: 'input-email',
      type: 'input',
      timestamp: 1712000000100,
      pageUrl: 'http://localhost:3000/login',
      locator: { strategy: 'label', value: 'Email' },
      value: 'q***@example.com',
      masked: true,
      fieldName: 'email',
    },
    {
      id: 'input-password',
      type: 'input',
      timestamp: 1712000000200,
      pageUrl: 'http://localhost:3000/login',
      locator: { strategy: 'label', value: 'Password' },
      value: '******',
      masked: true,
      fieldName: 'password',
    },
    {
      id: 'click-login',
      type: 'click',
      timestamp: 1712000000300,
      pageUrl: 'http://localhost:3000/login',
      locator: { strategy: 'role', value: 'button:로그인' },
      text: '로그인',
    },
    {
      id: 'req-login',
      type: 'network-request',
      timestamp: 1712000000320,
      requestId: 'req-login',
      method: 'POST',
      url: 'http://localhost:3000/api/auth/login',
      pageUrl: 'http://localhost:3000/login',
      resourceType: 'xhr',
      headers: { 'content-type': 'application/json' },
    },
    {
      id: 'res-login',
      type: 'network-response',
      timestamp: 1712000000460,
      requestId: 'req-login',
      status: 200,
      durationMs: 140,
      contentType: 'application/json',
    },
    {
      id: 'nav-products',
      type: 'navigation',
      timestamp: 1712000000600,
      pageUrl: 'http://localhost:3000/products',
      targetUrl: 'http://localhost:3000/products',
      trigger: 'history',
    },
    {
      id: 'click-existing-post',
      type: 'click',
      timestamp: 1712000000900,
      pageUrl: 'http://localhost:3000/products',
      locator: { strategy: 'role', value: 'link:JourneyForge roadmap' },
      text: 'JourneyForge roadmap',
    },
    {
      id: 'req-existing-post',
      type: 'network-request',
      timestamp: 1712000000920,
      requestId: 'req-existing-post',
      method: 'GET',
      url: 'http://localhost:3000/api/posts/99',
      pageUrl: 'http://localhost:3000/products',
      resourceType: 'fetch',
      headers: { accept: 'application/json' },
    },
    {
      id: 'res-existing-post',
      type: 'network-response',
      timestamp: 1712000001010,
      requestId: 'req-existing-post',
      status: 200,
      durationMs: 90,
      contentType: 'application/json',
    },
    {
      id: 'nav-existing-post',
      type: 'navigation',
      timestamp: 1712000001060,
      pageUrl: 'http://localhost:3000/posts/99',
      targetUrl: 'http://localhost:3000/posts/99',
      trigger: 'history',
    },
    {
      id: 'click-edit-post',
      type: 'click',
      timestamp: 1712000001260,
      pageUrl: 'http://localhost:3000/posts/99',
      locator: { strategy: 'role', value: 'link:수정하기' },
      text: '수정하기',
    },
    {
      id: 'nav-edit-post',
      type: 'navigation',
      timestamp: 1712000001350,
      pageUrl: 'http://localhost:3000/posts/99/edit',
      targetUrl: 'http://localhost:3000/posts/99/edit',
      trigger: 'history',
    },
    {
      id: 'input-title',
      type: 'input',
      timestamp: 1712000001550,
      pageUrl: 'http://localhost:3000/posts/99/edit',
      locator: { strategy: 'label', value: 'Title' },
      value: 'JourneyForge roadmap v2',
      masked: false,
      fieldName: 'title',
    },
    {
      id: 'input-content',
      type: 'input',
      timestamp: 1712000001750,
      pageUrl: 'http://localhost:3000/posts/99/edit',
      locator: { strategy: 'label', value: 'Content' },
      value: 'Write flow coverage now includes payload templates.',
      masked: false,
      fieldName: 'content',
    },
    {
      id: 'click-update',
      type: 'click',
      timestamp: 1712000001950,
      pageUrl: 'http://localhost:3000/posts/99/edit',
      locator: { strategy: 'role', value: 'button:저장' },
      text: '저장',
    },
    {
      id: 'req-update-post',
      type: 'network-request',
      timestamp: 1712000001965,
      requestId: 'req-update-post',
      method: 'PATCH',
      url: 'http://localhost:3000/api/posts/99',
      pageUrl: 'http://localhost:3000/posts/99/edit',
      resourceType: 'fetch',
      headers: { 'content-type': 'application/json' },
    },
    {
      id: 'res-update-post',
      type: 'network-response',
      timestamp: 1712000002145,
      requestId: 'req-update-post',
      status: 200,
      durationMs: 180,
      contentType: 'application/json',
    },
    {
      id: 'req-updated-detail',
      type: 'network-request',
      timestamp: 1712000002160,
      requestId: 'req-updated-detail',
      method: 'GET',
      url: 'http://localhost:3000/api/posts/99',
      pageUrl: 'http://localhost:3000/posts/99/edit',
      resourceType: 'fetch',
      headers: { accept: 'application/json' },
    },
    {
      id: 'res-updated-detail',
      type: 'network-response',
      timestamp: 1712000002240,
      requestId: 'req-updated-detail',
      status: 200,
      durationMs: 80,
      contentType: 'application/json',
    },
    {
      id: 'nav-updated-post',
      type: 'navigation',
      timestamp: 1712000002290,
      pageUrl: 'http://localhost:3000/posts/99',
      targetUrl: 'http://localhost:3000/posts/99',
      trigger: 'history',
    },
  ],
};
